# Generated by Django 3.2.5 on 2021-09-22 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 6, 48, 25, 160186, tzinfo=utc)),
        ),
    ]
